[package]
name = "gkr"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-bn254 = "0.5.0"
ark-ff = "0.5.0"
# strum = "0.27.1"
strum = { version = "0.25", features = ["derive"] }
strum_macros = "0.25" 